#!/usr/bin/env ruby
# frozen_string_literal: true

require './chat'
require 'rack'
require 'anycable'

# Turn AnyCable compatibility mode
LiteCable.anycable!

Anycable.configure do |config|
  config.connection_factory = Chat::Connection
  config.debug = true
end

Anycable::Server.start
